project:
  type: website

metadata-files:
  - reference/_sidebar.yml

website:
   navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: docs/index.qmd
      - text: "Documentation"
        href: reference/index.qmd


   sidebar:
    contents:
      - text: Home
        file: docs/index.qmd
      - text: API Reference
        file: reference/index.qmd
      - text: Contributing
        file: docs/contributing.qmd
      - text: License
        file: docs/license.qmd


format:
  html:
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  package: autoeda
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Summary statistics
      desc: Functions to perform automated exploratory data analysis.
      package: autoeda
      contents:
        - get_summary_df

    - title: Data inspection
      desc: Functions to inspect data for common issues.
      package: autoeda.inspect
      contents:
        - get_unary
        - get_high_cardinality

    - title: Missing data and outliers
      desc: Function to check amount of missing data in a DataFrame.
      package: autoeda.check_na_outlier
      contents:
        - check_na_outliers

    - title: Data plotting
      desc: Functions to create common plots for exploratory data analysis.
      package: autoeda.plot
      contents:
        - plot_correlation_heatmap
        - plot_histograms_by_target
