# get_summary_df { #autoeda.get_summary_df }

`get_summary_df`



## Functions

| Name | Description |
| --- | --- |
| [get_summary_df](#autoeda.get_summary_df.get_summary_df) | Returns a summary dataframe with the main statistics, datatypes, |

### get_summary_df { #autoeda.get_summary_df.get_summary_df }

```python
get_summary_df.get_summary_df(df, categorical_columns, numerical_columns)
```

Returns a summary dataframe with the main statistics, datatypes,
counts/missing values for numerical and categorical columns.

#### Parameters {.doc-section .doc-section-parameters}

| Name                | Type             | Description                                        | Default    |
|---------------------|------------------|----------------------------------------------------|------------|
| df                  | pandas.DataFrame | Input dataset for exploratory data analysis.       | _required_ |
| categorical_columns | list of str      | Names of columns treated as categorical variables. | _required_ |
| numerical_columns   | list of str      | Names of columns treated as numerical variables.   | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name           | Type             | Description                                                                                                                                             |
|----------------|------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| categorical_df | pandas.DataFrame | Summary dataframe for categorical columns, including: data types, non-null counts, missing values, and most frequent category.                          |
| numerical_df   | pandas.DataFrame | Summary dataframe for numerical columns, including: data types, non-null counts, missing values, mean, standard deviation, minimum, and maximum values. |